/*

 DEMOSCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbdk\gbdk\beantale\dialogue.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __demoscreen_h_INCLUDE
#define __demoscreen_h_INCLUDE

#define demoscreenWidth 20
#define demoscreenHeight 18
#define demoscreenBank 0

extern const unsigned char demoscreen[];

#endif

/* End of DEMOSCREEN.H */
