/*

 LOGOMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbdk\gbdk\beantale\logo.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __logomap_h_INCLUDE
#define __logomap_h_INCLUDE

#define logomapWidth 20
#define logomapHeight 18
#define logomapBank 0

extern const unsigned char logomap[];

#endif

/* End of LOGOMAP.H */
