/*

 TROUT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 7
   Tile set      : C:\gbdk\gbdk\beantale\dialogue.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __trout_h_INCLUDE
#define __trout_h_INCLUDE

#define troutWidth 20
#define troutHeight 7
#define troutBank 0

extern const unsigned char trout[];

#endif

/* End of TROUT.H */
